### ISSUE TITLE
7월 5주차

### ISSUE THREAD

**Issue by mia-slowalk** [slowalk/K-HERITAGE.TV.newsletter#29]
@misom-slowalk 미솜님 7월 5주차 썸네일 이미지 원본 [여기](https://drive.google.com/drive/folders/13NtSYZBaKQWG0-ISdfWw_LuocaxQfD3f?usp=sharing)로 전달드립니다!
 - 메인2 영상의 경우 이전에도 메인 섹션으로 들어갔던 적이 있어서 그대로 사용하면 될지만 확인 부탁드려요:)

**Comment by misom-slowalk** [comment]
@mia-slowalk 메인 첫번째 영상이었나요? 첫번째 메인 이미지 아니면 그대로 사용하시면 돼요 :)

**Comment by mia-slowalk** [comment]
@misom-slowalk 오 두번째 영상이었어요 미솜님! 확인 감사합니다:-D

**Comment by misom-slowalk** [comment]
@mia-slowalk 이미지 전달드려요 :)
[썸네일 이미지](https://drive.google.com/drive/folders/1DsfpfEEIqfZlRf7Jwjmj6kg1QsbN_eEv)

**Comment by mia-slowalk** [comment]
@misom-slowalk 미솜님 좀 전에 테스트메일 발송했는데요! 재단에서 추가로 넣어달라고 한 영상이 있어 아래 이미지에 라벨링 작업을 부탁드릴 수 있을까요?ㅠㅠ 금주의 픽 최상단에 들어가고 라벨명은 NEW 입니다!

- 문화유산채널이 제작지원에 함께한 영화가 베니스 국제영화제에 초청되었다고 해요. 관련 영상이 오늘 아침에 올라가는 바람에 뒤늦게 요청주신다고 하네요!;_; 
- 사선형 라벨이나 색상 등을 활용해서 기존 라벨보다 강조될 수 있으면 좋을 것 같은데 이건 미솜님 작업량 보시고 알려주셔요! 
<img width="742" alt="스크린샷 2022-07-28 오후 5 56 05" src="https://user-images.githubusercontent.com/88302128/181466017-e2b9c6bb-3b22-468f-93d7-64ce3222c351.png">

**Comment by misom-slowalk** [comment]
@mia-slowalk 미아님, 스티비에 이미지 수정해뒀고, 드라이브에도 파일 대치해놨어요! :)

**Comment by mia-slowalk** [comment]
@misom-slowalk 미솜님 확인했습니다!! 이미지 만들어주신거 예뻐요!! 적용해서 테스트메일 다시 발송하겠습니다:) 고생하셨어요
